/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Servlet.Office;

import Model.MailUtil;
import com.mongodb.BasicDBObject;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.servlet.RequestDispatcher;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.bson.Document;
import org.bson.types.ObjectId;

/**
 *
 * @author ranul
 */
public class SendMail extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet SendMail</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet SendMail at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        System.out.println("Start");
        String Reply = request.getParameter("Reply");
        String id = request.getParameter("_id");
        System.out.println(id);
        MongoClient mongoClient = MongoClients.create("mongodb://admin:p5Dy6BoofEB9JAeB@cers-shard-00-00-qwvj6.mongodb.net:27017,cers-shard-00-01-qwvj6.mongodb.net:27017,cers-shard-00-02-qwvj6.mongodb.net:27017/test?ssl=true&replicaSet=CERs-shard-0&authSource=admin&retryWrites=true&w=majority");
        MongoDatabase database = mongoClient.getDatabase("CERdb");

        MongoCollection collection = database.getCollection("orders");
//        String email = request.getParameter("Email");
/* PARAMETER 'Email' COMMENTTED TO PREVENT EMAILs SENT TO AUTOGENERATED EMAIL ADDRESSES IN DATABASE, 
* USING ADMIN EMAIL FOR DEVELOPMENT ONLY
         */
//        Reply = "Available";
        String email = "cers.developer@gmail.com";
        if ("Available".equals(Reply)) {
            System.out.println("Available");
            try {
//                MailUtil.SendEmailAvailable(email);
                BasicDBObject query = new BasicDBObject().append("_id",new ObjectId(id));
                BasicDBObject newDocument = new BasicDBObject();
                newDocument.append("$set", new BasicDBObject().append("Status", "Done"));
                collection.updateOne(query, newDocument);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        } else if ("NotAvailable".equals(Reply)) {
            System.out.println("NotAvailable");
            try {
                BasicDBObject query = new BasicDBObject().append("_id", new ObjectId(id));
                BasicDBObject newDocument = new BasicDBObject();
                newDocument.append("$set", new BasicDBObject().append("Status", "Rejected"));
                collection.updateOne(query, newDocument);
//                MailUtil.SendEmailUnAvailable(email);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
        System.out.println("end");
        System.out.println(Reply + email);
        BasicDBObject query = new BasicDBObject();
        query.append("Status",new BasicDBObject("$ne", "Done"));
        FindIterable document = collection.find(query);
        ArrayList<Document> orders = new ArrayList<Document>();
        document.into(orders);
        request.setAttribute("orders", orders);
        RequestDispatcher rd = getServletContext().getRequestDispatcher(
                "/Office/Order.jsp");
        rd.forward(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
